[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = {  version = "0.8.3", features = ["macros"]}
axum-extra = {version = "0.10.1", features = ["typed-header"]}
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
mp4 = "0.14.0"
serde = { version = "1.0" }
serde_json = "1.0"
tokio = { version = "1" }
tower-http = { version = "0.6.2", features = ["validate-request"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
webrtc = { version = "0.12.0" }

# Optional: For specific depacketizers if not easily accessible via webrtc::rtp::codecs::*
# webrtc-rtp = "0.8" # Check version matching webrtc
